version: '3'
services:
  directus:
    image: directus/directus:10.9.2
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    environment:
      KEY: 'B807B41D-425F-41A4-AB7C-7FEDC2B10FF8'
      SECRET: 'C576AE7E-3569-4E86-888E-662B4D1A6615'

      DB_CLIENT: 'pg'
      DB_HOST: 'aws-0-us-east-1.pooler.supabase.com'
      DB_PORT: '5432'
      DB_DATABASE: 'postgres'
      DB_USER: 'postgres.xgywygponsfjclsgakcn'
      DB_PASSWORD: 'vxo*nvUPg2xogEzxrrvT3BRdyeM-yyqnVR'

      CACHE_ENABLED: 'false'

      ADMIN_EMAIL: 'tom@kenkeldesign.com'
      ADMIN_PASSWORD: 'c/(JyQ27qhfuaXjYj6rut'

      # These is helpful for local developement but should probably be removed in production
      CORS_ENABLED: 'true'
      REFRESH_TOKEN_COOKIE_DOMAIN: 'localhost'
      EXTENSIONS_AUTO_RELOAD: 'true'

      WEBSOCKETS_ENABLED: 'true'
      # The default config prevents importing files from 0.0.0.0. See https://docs.directus.io/self-hosted/config-options.html#security . This can be removed in production but in local development it is recommended to keep it so you can import logos from Organization > website.
      IMPORT_IP_DENY_LIST: ''

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: 'https://studio.kenkeldesign.com'
